### ISSUE TITLE
Add a 'quit' button for the game

### ISSUE THREAD

**Issue by TAGraves** [YMCACOLUMBUS/activescience-issues#15]
> Is there a way to add a “quit” button for the game? Some children who were having trouble wanted to stop and move forward.

Is this still desired after we added the instructions for how to play the game?

**Comment by scottdebney** [comment]
Maybe a solution is after certain number of seconds, say 20 we could have a quit button appear?  What we would hate to happen is people just skip the games altogether and not tie the data together? Because they could be like "yes, I'll score less today" and quit the game ?   I mean they could do that anyway, because they could not try, but at least they have to wait a few seconds which makes them try a bit?

**Comment by Jacquelyn-Rudis** [comment]
I think that a timer countdown will help rather than adding a quit button. They have trouble the first few times they play the game but then they seem to get it, I would want them to have to try to learn how to play it. If the timer is added at least they will know how long they have to wait if they decide to stop trying.  So no "quit" button needed. Thanks!
